server:
  port: 8081
spring:
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/dafuweng?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 616131
    driver-class-name: com.mysql.cj.jdbc.Driver
  # redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
    timout: 10000
    expire: 60000

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml ## 配置MyBatis-Plus扫描Mapper文件的位置
  type-aliases-package=com: com.dafuweng.entity

# java web token配置
jwt:
  secret: com.dafuweng
  expiration: 1800000

# request配置
request:
  login:
    url: /api/user/login